name: .Net application scan with Jfrog Xray
on:
  push:
  workflow_dispatch:

jobs:
  Jfrog-configuration:
    runs-on: ubuntu-latest
    steps:
      - name: configure Jfrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
          include-prerelease: true
          fetch-depth: 0
        
      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: To specify the .sln file
        run: dotnet publish eShopOnWeb.sln -c Release -o out

      - name: Scan the .Net application
        run: jf audit --watches "demo"
      