name: .Net application scan with Jfrog Xray
on:
  push:
  workflow_dispatch:

jobs:
  Jfrog-configuration:
    runs-on: ubuntu-latest
    steps:
      - name: configure Jfrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
      
      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: to specify the .sln file
        uses: dotnet publish eShopOnWeb.sln -c Release -o out

      - name: Scan the .Net application
        run: jf audit --watches "demo"
      